# Generated by Django 4.2.21 on 2025-05-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGE', models.TextField()),
                ('BILL_ID', models.TextField(unique=True)),
                ('BILL_NO', models.IntegerField()),
                ('BILL_KND', models.TextField()),
                ('BILL_NM', models.TextField()),
                ('PPSR_NM', models.TextField(blank=True, null=True)),
                ('PPSR_KND', models.TextField()),
                ('PPSR_DT', models.DateField(blank=True, null=True)),
                ('PPSR_SESS', models.IntegerField(blank=True, null=True)),
                ('JRCMIT_NM', models.TextField(blank=True, null=True)),
                ('JRCMIT_CMMT_DT', models.DateField(blank=True, null=True)),
                ('JRCMIT_PRSNT_DT', models.DateField(blank=True, null=True)),
                ('JRCMIT_PROC_DT', models.DateField(blank=True, null=True)),
                ('JRCMIT_PROC_RSL', models.TextField(blank=True, null=True)),
                ('LAW_CMMT_DT', models.DateField(blank=True, null=True)),
                ('LAW_PRSNT_DT', models.DateField(blank=True, null=True)),
                ('LAW_PROC_DT', models.DateField(blank=True, null=True)),
                ('LAW_PROC_RSLT', models.TextField(blank=True, null=True)),
                ('RGS_PRSNT_DT', models.DateField(blank=True, null=True)),
                ('RGS_RSLN_DT', models.DateField(blank=True, null=True)),
                ('RGS_CONF_NM', models.TextField(blank=True, null=True)),
                ('RGS_CONF_RSLT', models.TextField(blank=True, null=True)),
                ('GVRN_TRSF_DT', models.DateField(blank=True, null=True)),
                ('PROM_LAW_NM', models.TextField(blank=True, null=True)),
                ('LAW_SECTOR', models.TextField(blank=True, null=True)),
                ('PROM_DT', models.DateField(blank=True, null=True)),
                ('PROM_NO', models.IntegerField(blank=True, null=True)),
                ('LINK', models.TextField()),
                ('PROC_RSLT', models.TextField()),
                ('SUMMARY', models.TextField(blank=True, null=True)),
                ('COMMENTS', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
