# Generated by Django 4.2.21 on 2025-05-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='LINK',
            new_name='LINK_URL',
        ),
        migrations.AlterField(
            model_name='bill',
            name='BILL_NO',
            field=models.TextField(),
        ),
    ]
