# Generated by Django 4.2.21 on 2025-05-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_link_bill_link_url_alter_bill_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='AGE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='BILL_KND',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='BILL_NM',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='BILL_NO',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='LINK_URL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='PPSR_KND',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='PROC_RSLT',
            field=models.TextField(blank=True, null=True),
        ),
    ]
